# Generated by Django 3.2.25 on 2024-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240517_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uodated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
