# Generated by Django 3.2.25 on 2024-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240519_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='challenge',
        ),
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.FloatField(default=3.0),
        ),
    ]
